#!/bin/bash

DOTFILES_HOME=~/dotfiles
HOMESHICK_DIR_PATH=$DOTFILES_HOME/homeshick

function setup {
	vim
	pushd $DOTFILES_HOME > /dev/null
	git submodule init
	git submodule update
	pushd $HOMESHICK_DIR_PATH > /dev/null
	./homeshick clone ~/dotfiles
	./homeshick  symlink dotfiles
	popd > /dev/null
	popd > /dev/null
}

function vim {
	if [ ! -d $DOTFILES_HOME/vim73 ]; then
		pushd $DOTFILES_HOME > /dev/null
		curl ftp://ftp.vim.org/pub/vim/unix/vim-7.3.tar.bz2 | tar xj
		pushd vim73 > /dev/null
		./configure --with-features=big --enable-pythoninterp
		make
		popd > /dev/null
		popd > /dev/null
	fi
}

function push {
	local login="amos@$2"
	echo "$login"
	scp ~/.ssh/github "$login:~/.ssh/id_rsa"
	echo "git clone git://github.com/squamos/dotfiles.git && dotfiles/dotfiles setup" | ssh $login /bin/bash
}

case $1 in
	setup) setup   ;;
	push)  push $@ ;;
	vim)   vim     ;;
esac
