#!/bin/bash

BASHRC_DISPATHCH_FILEPATH=~/dotfiles/bashrc_dispatch/bashrc_dispatch

ln -s $BASHRC_DISPATHCH_FILEPATH ~/.bashrc
ln -s $BASHRC_DISPATHCH_FILEPATH ~/.bash_profile
ln -s $BASHRC_DISPATHCH_FILEPATH ~/.profile
ln -s $BASHRC_DISPATHCH_FILEPATH ~/.bash_login

chmod +x ~/.bashrc
chmod +x ~/.bash_profile
chmod +x ~/.profile
chmod +x ~/.bash_login
